/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.freng.view;

/**
 *
 * @author phelype
 */
public class viewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form viewPrincipal
     */
    public viewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonColetores = new javax.swing.JButton();
        jButtonImpressoras = new javax.swing.JButton();
        jButtonRelacoes = new javax.swing.JButton();
        jButtonComputadores = new javax.swing.JButton();
        jButtonBaterias = new javax.swing.JButton();
        jButtonCadastros = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patrimônio");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonColetores.setIcon(new javax.swing.ImageIcon("/home/phelype/Pictures/Icons Patrimonio/iloveimg-resize/ikon.jpg")); // NOI18N
        jButtonColetores.setText("  Coletores");
        jButtonColetores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColetoresActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonColetores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, 130, -1));

        jButtonImpressoras.setIcon(new javax.swing.ImageIcon("/home/phelype/Pictures/Icons Patrimonio/iloveimg-resize/Seiko_MPUL465.jpg")); // NOI18N
        jButtonImpressoras.setText("Impressoras");
        getContentPane().add(jButtonImpressoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, -1));

        jButtonRelacoes.setText("Relações");
        jButtonRelacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelacoesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 130, 40));

        jButtonComputadores.setText("Computador");
        getContentPane().add(jButtonComputadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 100, -1));

        jButtonBaterias.setText("Baterias");
        jButtonBaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBateriasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 100, -1));

        jButtonCadastros.setText("Cadastros");
        getContentPane().add(jButtonCadastros, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 100, -1));

        jButtonSair.setText("Sair");
        getContentPane().add(jButtonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 90, 30));

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");

        jMenuItem2.setText("Sobre");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(284, 245));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButtonBateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBateriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBateriasActionPerformed

    private void jButtonColetoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColetoresActionPerformed
        viewColetores coletores = new viewColetores();
        coletores.setVisible(true);
        
    }//GEN-LAST:event_jButtonColetoresActionPerformed

    private void jButtonRelacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRelacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBaterias;
    private javax.swing.JButton jButtonCadastros;
    private javax.swing.JButton jButtonColetores;
    private javax.swing.JButton jButtonComputadores;
    private javax.swing.JButton jButtonImpressoras;
    private javax.swing.JButton jButtonRelacoes;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
